### ISSUE TITLE
The maximum number of features is always 255

### ISSUE THREAD

**Issue by ngunsu** [kmyid/TILDE#1]
In  sortFeaturesSS_noAbs.m

stop = uint8(min([nbFeat size(v,2) ix]));

Because of the casting to uint8, the max number of features is 255 instead of the 1000 in the examples.

**Comment by kmyi** [comment]
Sorry for the bug.
The bug is now fixed with commit ffeea7bcd6f1b2da441d5d1cb74739ee15518952
Thank you for the report

Best Regards,
Authors of TILDE
