### ISSUE TITLE
matlab evaluation error

### ISSUE THREAD

**Issue by hanghoo** [kmyid/TILDE#3]
Hello,kmyid.
I  put Chamonix, Courbevoie, Frankfurt, Mexico, Panorama, StLouis folders at project root/data/, and run evaluate_WebcamDataset_2percents.m. There are some errors. 
/bin/bash: /home/hoo104/TILDE/matlab/external/external_codes/methods/opencvKeypointDetector: cannot execute binary file: Exec format error
Error using fscanf
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in loadFeatures (line 3)
    dim = fscanf(fid, '%f',1);

Error in getKeypoints_SIFT (line 44)
        [feat, ~, ~] = loadFeatures(out);

Error in evaluateKeyPointsCompWithDir_ratio (line 151)
            features{i_method}{i_img} = eval(['getKeypoints_' keyptMethodName
            '(list_img_info{i_img},p)']);

Error in computeKP (line 59)
        res = evaluateKeyPointsCompWithDir_ratio(combinations{idxComb,1},
        combinations{idxComb,2}, combinations{idxComb,3}, parameters);

Error in evaluate_WebcamDataset_2percents (line 53)
Allrepeatability = computeKP(parameters);

**Comment by kmyi** [comment]
Hello,

> /bin/bash: /home/hoo104/TILDE/matlab/external/external_codes/methods/opencvKeypointDetector: cannot execute binary file: Exec format error

You need to compile the binary properly. See readme.

Kwang

**Comment by hanghoo** [comment]
Hello, kmyid
Running link.m is compiling the binary? And running link.m isn't a right method to solve it. 
If not, I really don't know how to compile the binary.

thanks for your reply.

**Comment by kmyi** [comment]
Hi,

Try running make.m. 

Kwang
_________  

Kwang Moo Yi, Ph.D., 
PostDoc @EPFL CVLab
Tell: +41 21 693 67 16

**Comment by hanghoo** [comment]
Hello, kmyid
The make.m is in /TILDE/src/make.m. Thus, there is no content in it.
you reply quickly,thanks.

**Comment by kmyi** [comment]
I see, so it was never finished then.
I think you’ll have to do it manually then. 
Go to the matlab/external/external_codes/* and type make

Frankly, It’s been two years so I honestly only have vague memory of the usage.

Kwang

_________  

Kwang Moo Yi, Ph.D., 
PostDoc @EPFL CVLab
Tell: +41 21 693 67 16

**Comment by hanghoo** [comment]
Yes, it is hard to remember any part of the codes which wrote 2 years ago.
But I do not understand 
> "Go to the matlab/external/external_codes/* and type make".

And I don't figure out exactly how to do it. I hope you can explain that.

**Comment by kmyi** [comment]
Hi, 

If you have no idea what I am talking about, then I think you should have a look at how compiling works in Nix systems with gnu make. I'll leave you to figure this one out.

Cheers,
Kwang

**Comment by hanghoo** [comment]
well,I know little about compiling works about c++, but I don't see any CMakeLists in the matlab/external/external_codes/*
I guess there are some misunderstandings here.

**Comment by kmyi** [comment]
Just build with the provided makefiles in each directory

**Comment by hanghoo** [comment]
I try to make it. Thank you very much.
