### ISSUE TITLE
How do I create a SURF descriptor on TILDE keypoints for matching?

### ISSUE THREAD

**Issue by uzair789** [kmyid/TILDE#4]
Hi, I am trying to match two scenes by extracting descriptor around the TILDE keypoints. The matlab code generates the x,y locations for the TILDE keypoints successfully. How can I use these x,y cordinates to generate SURF descriptors at these locations? 

Since you have already done this for results in your paper, do you have any function in the code for doing this?

Thanks.

**Comment by kmyi** [comment]
Hi, unfortunately, this was done quite some time ago, and I have moved to another institution. I don't think I can help you on this. If you want, you can try comparing with the LIFT keypoints and Descriptors, which is a follow-up work. Closing the issue for now.

Thanks,
KWang
