### ISSUE TITLE
Draw lines to match point

### ISSUE THREAD

**Issue by Ahmedest61** [kmyid/TILDE#5]
Hi, I found this detector very interesting. I need to draw lines between the common features points of two images using MATLAB code (also shown in the paper). I made use of demo.m to find features points and now need to draw a line. How can it be done?

**Comment by kmyi** [comment]
Hi, I'm sorry but that part you'll have to study the code an do it your self. I don't have a demo script for it. It should be easy to do, just standard matching and drawing.
