### ISSUE TITLE
TILDE dataset link not working

### ISSUE THREAD

**Issue by johnwlambert** [kmyid/TILDE#6]
Hi, I tried the link [http://cvlab.epfl.ch/research/tilde](http://cvlab.epfl.ch/research/tilde) to download the TILDE dataset, but couldn't access it. Is the data accessible at another location? Thanks!

I think this link is also down: [http://cvlab.epfl.ch/research/detect/orientation](http://cvlab.epfl.ch/research/detect/orientation).

**Comment by kmyi** [comment]
Seems like there was a refactor on the cvlab website ;-)

See https://www.epfl.ch/labs/cvlab/research/descriptors-and-keypoints/research-detect-orientation/

**Comment by johnwlambert** [comment]
Got it, thanks very much @kmyid !
